#!/bin/bash

set +xe

CI_NUM=56143

cd ${CI_NUM}/p4-programs/fxp-net-scenarios/fxp-net_linux-networking-v3/
rm -rf lnw-v3

p4c --target idpf --arch pna -I/usr/lib \
    -I/usr/share/p4c/p4include \
    -I$/usr/share/p4c/idpf-lib \
    --package-by-domain \
    --p4runtime-files ./lnw-v3/p4Info.txt \
    -Xp4c "--no-pedantic  --ptype-autogen off \
    --context ./lnw-v3/context.json \
    --bfrt ./lnw-v3/tdi.json"  \
    --npic --format csr --pkg-name "lnpvg_ipsec_11" \
    --pkg-version  "3.01.24.4" \
    --save-temps \
    fxp-net_linux-networking-v3.p4 -o lnw-v3

