#!/bin/bash

# This script runs all the steps in sequence
# Review config.env before running for environment details

# 1. Reboot IMC/ACC + setup P4 pkg from target_copy folder

if ! ./1-setup-imc-acc.sh; then
    echo " >>> 1-setup-imc-acc.sh exited with error status. Correct errors before proceeding. Stopping full-bringup."
    exit 1
fi
echo "================= 1-setup-imc-acc.sh completed ============"

# 2. Init ACC, setup comms channel, start IDPF driver on host

if ! ./2-init-acc.sh; then
    echo " >>> ./2-init-acc.sh exited with error status. Correct errors before proceeding. Stopping full-bringup."
    exit 1
fi
echo "================= 2-init-acc.sh completed ================="

# 3. Program p4 tables, run OVS and setup networking
#./3-auto.sh
#./3-auto-vxlan-ipsec-tunnel.sh
#./3-auto-dual-port-ipsec-tunnel.sh
#echo "================= 3-auto.sh completed ====================="
